Innkalling_FB2_2024-04-02-med-vedlegg.pdf: Innkalling_FB2_2024-04-02.pdf Makefile
	pdftk I=Innkalling_FB2_2024-04-02.pdf R=Revisjonsberetning_2023_Sameiet_Folke_Bernadottes_vei_2.pdf A=arsregnskap_Sameiet_Folke_Bernadottes_vei_2_2023.pdf T=Tilbud_laas_og_nokkel.pdf V=vedlegg-1_Foresprsel_besvart.pdf cat I R A T1 T2 T4 T5 V output Innkalling_FB2_2024-04-02-med-vedlegg.pdf verbose

Innkalling_FB2_2024-04-02.pdf: Innkalling_FB2_2024-04-02.tex
	lualatex Innkalling_FB2_2024-04-02.tex

